### PR TITLE
Sync up with react select

### PR DESCRIPTION
**Pull request by AndreiRailean**
Merge latest master of react-select into react-select-plus

Manually resolved conflicts. `yarn test` had no errors. 
Not sure what other steps are required to make it mergeable.

Doing my part to keep two projects in sync.

### CODE REVIEW

**Comment by zgredzik** [comment]
Out of sheer curiosity: is there any reason for developing this component as a separate project instead of making a PR to the original JedWatson/react-select ?
I'm interested in the option group support but I am a bit worried about the two projects diverging.
It is a bit inconvenient to monitor the state of two very similar yet separate solutions (checking for bug fixes, api changes, etc.).

**Comment by AndreiRailean** [comment]
My understanding is that JedWatson is very picky about the features he wants to have in react-select. Have a look at the number of issues and pull requests on react-select repo to understand why someone may find it easier to fork.

**Comment by TrevorBurnham** [comment]
> is there any reason for developing this component as a separate project instead of making a PR to the original JedWatson/react-select ?

Here's the ticket for option groups in JedWatson/react-select: https://github.com/JedWatson/react-select/issues/59
Here's the PR that was the kernel of react-select-plus (Colby and I both work at HubSpot): https://github.com/JedWatson/react-select/pull/480

We'd be thrilled to see react-select incorporate the features we need. We've always hoped that this fork would be a temporary solution. Unfortunately, development on JedWatson/react-select has largely stalled for the time being.

**Comment by TrevorBurnham** [comment]
As to this ticket, I appreciate it but won't have time to review it until next week. Thank you for your patience.

**Comment by iChip** [comment]
Last comment was several months ago - any update on syncing with react-select?

**Comment by TrevorBurnham** [comment]
Sorry for the delay here. I have an open PR to sync up with react-select RC10: #96 Any eyes on that branch would be appreciated!

**Pull request closed without merging**
