### PR TITLE
Merge master from JedWatson/react-select

### PR DESCRIPTION
**Pull request by Xenza**
New commits make openOnFocus work correctly.

### CODE REVIEW

**Comment by enf0rc3** [comment]
+1 please merge, we have had this bug for a while and had to write a work around.

**Comment by TrevorBurnham** [comment]
I was hoping there would be an upstream release soon, but I guess there's no sign of that. I'll merge later this week.

**Comment by TrevorBurnham** [comment]
Merged and published to npm as version `1.0.0-rc.3.patch3`.

**Comment by enf0rc3** [comment]
@TrevorBurnham  Thanks for that, our work around broke, but overall we got an extra feature working, so lose win win.

**Pull request merged**
