### PR TITLE
fix dragging errors in OptionGroup

### PR DESCRIPTION
**Pull request by nathanharper**
Hi, would you consider this PR? I was getting errors related to a dragging property on the OptionGroup class, and this should fix it.

### CODE REVIEW

**Comment by emartini** [comment]
I'm getting a lot of errors due this bug. It would be great if this PR can be merged

**Comment by nathanharper** [comment]
I hope this library is still maintained... unfortunately I can't guarantee long-term maintenance on this project myself, but if anybody needs a quick fix you're welcome to add my built branch to your dependencies, which is what I'm doing right now.

"react-select-plus": "git://github.com/nathanharper/react-select-plus.git#built"

**Comment by Friss** [comment]
@TrevorBurnham @banderson

**Comment by nathanharper** [comment]
Closing this since it's super old in JavaScript years and the functionality has since been added to `react-select`

**Pull request closed without merging**
